version: "3.5"

services:

  db:
    container_name: "db"
    restart: always
    env_file: .env
    build:
      context: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

  phpmyadmin:
    container_name: "phpmyadmin"
    restart: always
    env_file: .env
    build:
      context: ./requirements/bonus/phpmyadmin
    networks:
      - inception
    volumes:
      - phpma_data:/var/www/phpmyadmin
    depends_on:
      - db

  wordpress:
    container_name: "wordpress"
    restart: always
    env_file: .env
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - db

  nginx:
    container_name: "nginx"
    restart: always
    env_file: .env
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress:ro
      - phpma_data:/var/www/phpmyadmin:ro
    networks:
      - inception
    depends_on:
      - phpmyadmin
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/database'
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/wordpress'
  phpma_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/phpmyadmin'
