version: "3.5"

services:
#  wordpress:
#    container_name: "wordpress"
#    image: wordpress:latest
#    restart: always
#    volumes:
#      - "db_data:/var/lib/mysql"

  db:
    container_name: "db"
    build: database
    restart: always
#    volumes:
#      - "db_data:/var/lib/mysql"

volumes:
  db_data: {}
  wp_data: {}
