version: "3.5"

services:

  db:
    container_name: "db"
#    restart: always
    env_file: .env
    build:
      context: database
      args:
        DB_PASS: ${DB_PASS}
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

#  phpmyadmin:
#    container_name: "pma"
#    restart: always
#    env_file: .env
#    build:
#      context: phpmyadmin
#    networks:
#      - inception

  wordpress:
    container_name: "wordpress"
#    restart: always
    env_file: .env
    build:
      context: wordpress
#    volumes:
#      - wp_data:/var/www
    networks:
      - inception

  nginx:
    container_name: "nginx"
#    restart: always
    env_file: .env
    build:
      context: nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception


networks:
  inception:
    driver: bridge

volumes:
  db_data: {}
  wp_data: {}
