version: "3.5"

services:

  db:
    container_name: "db"
    restart: always
    env_file: .env
    build:
      context: database
      args:
        DB_PASS: ${DB_PASS}
        DB_USER: ${DB_USER}
        DB: ${DB}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

  phpmyadmin:
    container_name: "pma"
    restart: always
    env_file: .env
    build:
      context: phpmyadmin
    ports:
      - "8042:80"
    networks:
      - db_net

  wordpress:
    container_name: "wp"
#    restart: always
    env_file: .env
    build:
      context: wordpress
    ports:
      - "8043:80"
    networks:
      - db_net

  nginx:
    container_name: "nginx"
#    restart: always
    env_file: .env
    build:
      context: nginx
    volumes:
      - ${CERT_PATH}:/etc/ssl/private/:ro
    ports:
      - "443:443"


networks:
  db_net:
    driver: bridge

volumes:
  db_data: {}
  wp_data: {}
